///////////////////////////////////////////////////////////////////////////////
// AdsTalkerClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "AdsTalkerClassFactory.h"
#include "AdsTalkerServices.h"
#include "AdsTalkerVersion.h"
#include "AdsTalker.h"

BEGIN_CLASS_MAP(CAdsTalkerClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_AdsTalkerCAdsTalker, SRVNAME_ADSTALKER "!CAdsTalker", CAdsTalker)
///</AutoGeneratedContent>
END_CLASS_MAP()

CAdsTalkerClassFactory::CAdsTalkerClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_ADSTALKER)); 
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(AdsTalker));
#endif //defined(TCDBG_UNIT_VERSION)
}

