///////////////////////////////////////////////////////////////////////////////
// AdsTalkerInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "AdsTalkerServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
